import { Inter } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const switchLanguage = (lang) => setLanguage(lang);
export default function RootLayout({ children }) {
  return (
    <LanguageProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </LanguageProvider>
  );
}
